const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID ?? "";

export const SCHEMAS = {
  ARTICLES: {
    id: "articles",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "title", type: "string", required: true },
      { key: "slug", type: "string", required: true },
      { key: "summary", type: "string", required: true },
      { key: "content", type: "string", required: true },
      { key: "bulletPoints", type: "string[]", required: false },
      { key: "audioUrl", type: "string", required: false },
      { key: "coverImage", type: "string", required: false },
      { key: "category", type: "string", required: true },
      { key: "tags", type: "string[]", required: false },
      { key: "source", type: "string", required: true },
      { key: "sourceUrl", type: "string", required: true },
      { key: "viralScore", type: "number", required: false },
      { key: "headlineAlternatives", type: "string[]", required: false },
      { key: "status", type: "string", required: true },
      { key: "isSponsored", type: "boolean", required: false },
      { key: "sponsoredLabel", type: "string", required: false },
      { key: "seoMetaDescription", type: "string", required: false },
      { key: "seoKeywords", type: "string[]", required: false },
      { key: "publishedAt", type: "datetime", required: false },
      { key: "viewCount", type: "number", required: false },
      { key: "readTimeMinutes", type: "number", required: false },
    ],
  },
  USERS: {
    id: "users",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "nickname", type: "string", required: false },
      { key: "avatarUrl", type: "string", required: false },
      { key: "preferredCategories", type: "string[]", required: false },
      { key: "isAdmin", type: "boolean", required: false },
    ],
  },
  COMMENTS: {
    id: "comments",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "articleId", type: "string", required: true },
      { key: "userId", type: "string", required: true },
      { key: "text", type: "string", required: true },
      { key: "isModerated", type: "boolean", required: false },
    ],
  },
  GAMIFICATION: {
    id: "gamification",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "userId", type: "string", required: true },
      { key: "xp", type: "number", required: false },
      { key: "level", type: "number", required: false },
      { key: "streak", type: "number", required: false },
      { key: "lastActiveDate", type: "string", required: false },
      { key: "badgeIds", type: "string[]", required: false },
      { key: "totalReadTime", type: "number", required: false },
      { key: "totalComments", type: "number", required: false },
      { key: "totalShares", type: "number", required: false },
    ],
  },
  BADGES: {
    id: "badges",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "name", type: "string", required: true },
      { key: "description", type: "string", required: true },
      { key: "icon", type: "string", required: true },
      { key: "requiredXp", type: "number", required: false },
      { key: "category", type: "string", required: false },
    ],
  },
  NEWSLETTER: {
    id: "newsletter",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "email", type: "string", required: true },
      { key: "isActive", type: "boolean", required: false },
      { key: "subscribedAt", type: "datetime", required: false },
    ],
  },
  BANNERS: {
    id: "banners",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "advertiser", type: "string", required: true },
      { key: "imageUrl", type: "string", required: true },
      { key: "targetUrl", type: "string", required: true },
      { key: "position", type: "string", required: true },
      { key: "startDate", type: "datetime", required: true },
      { key: "endDate", type: "datetime", required: true },
      { key: "price", type: "number", required: false },
      { key: "isActive", type: "boolean", required: false },
      { key: "impressions", type: "number", required: false },
      { key: "clicks", type: "number", required: false },
    ],
  },
  SPONSORED: {
    id: "sponsored",
    databaseId: DATABASE_ID,
    attributes: [
      { key: "company", type: "string", required: true },
      { key: "briefing", type: "string", required: true },
      { key: "articleId", type: "string", required: false },
      { key: "status", type: "string", required: true },
      { key: "price", type: "number", required: false },
      { key: "publishedAt", type: "datetime", required: false },
    ],
  },
} as const;